### DISCUSSION TITLE
an easier way to spin up evershop with docker

### DISCUSSION THREAD

**Discussion by Hanibachi** [evershopcommerce/evershop#678] [Show and tell]
as a less "tech savvy" person, it took me a while to get this up and running properly so i suggest the devs would improve the documentation a bit , after plenty of trial and error i landed on the following steps :

simply create the following files in the same directory :

**Dockerfile**
```
FROM node:22-alpine
# install some necessary commandline tools to make debuging easier
RUN apk add bash git curl nano sed
# create the evershop app directory
RUN npx create-evershop-app app
# set the working directory
WORKDIR /app
# create the recommended directory structure
RUN mkdir themes extensions media translations config
# add the user creation and password change commands to the package.json
RUN sed -i '9i\    "user:create": "evershop user:create",' package.json
RUN sed -i '10i\   "user:changePassword": "evershop user:changePassword",' package.json
# run the setup command
RUN npm run setup
# build the app
RUN npm run build
# expose the port 80 (not entirely sure if this is necessary)
EXPOSE 80
# make sureto create the admin user
ENTRYPOINT [ "sh", "-c", "npm run user:create -- --email ${ADMIN_EMAIL} --password ${ADMIN_PASSWORD} --name ${ADMIN_NAME}" ]
# create the admin user and start the app (this needs some furthure tweaking)
CMD  ["npm", "run", "start"]
```

**compose.yaml**
```
services:
  app:
    container_name: evershop
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_NAME: evershop
    restart: unless-stopped
    environment:
      # setup the environment variables for database connection
      DB_HOST: postgres
      DB_PORT: 5432
      DB_PASSWORD: changeme
      DB_USER: evershop
      DB_NAME: evershop
      # setup the environment variables for the admin user
      ADMIN_NAME: admin
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: changeme
    # wait untill the database starts
    depends_on:
      - db
    ports:
      - 3000:3000 # {external port:internal container port}
    # uncomment the following lines if you want to access the app files more easily
    # volumes:
    #   - ./config:/app/config
    #   - ./extensions:/app/extensions
    #   - ./themes:/app/themes
    #   - ./translations:/app/translations
    #   - ./media:/app/media
    #   - ./public:/app/public

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: evershop
      POSTGRES_DB: evershop

volumes:
  postgres-data:
```

run : `docker compose up -d`

and you should be set to go.
